
package xu.sheng.jiang.web_client.xu.sheng.jiang.operation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://operation.jiang.sheng.xu/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
	private xu.sheng.jiang.web_client.xu.sheng.jiang.operation.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
	public Exception_Exception(String message, xu.sheng.jiang.web_client.xu.sheng.jiang.operation.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
	public Exception_Exception(String message, xu.sheng.jiang.web_client.xu.sheng.jiang.operation.Exception faultInfo,
			Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: xu.sheng.jiang.operation.Exception
     */
	public xu.sheng.jiang.web_client.xu.sheng.jiang.operation.Exception getFaultInfo() {
        return faultInfo;
    }

}
